# Global Underwriter configuration
global:
  privateKey: ""      # The privateKey of the account that will be submitting the underwrites
  logLevel: "debug"
  blockDelay: 5       # Delay with which to process the chain blocks. Use this to prevent handling
                      # blocks that eventually reorg.
                      # TODO If the 'monitor' service is moved to the Relayer, this config must
                      # TODO be implemented on the 'listener' directly.

  # TODO the monitor should be moved to the 'Relayer'
  monitor:
    interval: 5000    # Interval at which to update the chains status fromt the RPCs

  listener:
    processingInterval: 100     # Throttle for the Listener main 'run' loop
    maxBlocks: 1000             # Maximum number of blocks to query in a single call

  underwriter:
    retryInterval: 30000        # Time to wait before retrying an underwrite
    processingInterval: 100     # Throttle for the Underwriter main 'run' loop
    maxTries: 3                 # Maximum tries for an underwrite
    maxPendingTransactions: 50  # Maximum number of orders within the 'underwrite' pipeline
    underwriteBlocksMargin: 50  # Number of blocks after a swap's execution before which it is
                                # allowed to be underwritten.
    maxSubmissionDelay: 300000  # Maximum time for the wallet to submit the 'underwrite' transaction.

    lowTokenBalanceWarning: "1000000000000000000"  # Token balance below which a 'low balance' warning is emitted.
    tokenBalanceUpdateInterval: 50   # Number of transactions after which to update the Underwriter token balance from the rpc. 

  expirer:
    # ! The following properties default to the values of the 'underwriter' if missing
    retryInterval: 30000        # Time to wait before retrying an expiry
    processingInterval: 100     # Throttle for the Expirer main 'run' loop
    maxTries: 3                 # Maximum tries for an expiry
    maxPendingTransactions: 50  # Maximum number of orders within the 'expire' pipeline
    expireBlocksMargin: 500     # Number of blocks before the expiry deadline at which to expire
                                # an underwrite (only applies to underwrites by this underwriter)

  wallet:
    retryInterval: 30000        # Time to wait before retrying a failed transaction
    processingInterval: 100     # Throttle for the Wallet main 'run' loop
    maxTries: 3                 # Maximum tries for a transaction
    maxPendingTransactions: 50  # Maximum number of transactions within the 'submit' pipeline
    confirmationTimeout: 90000  # Timeout for a transaction to confirm

    lowGasBalanceWarning: "1000000000000000000"  # Gas balance below which a 'low balance' warning is emitted.
    gasBalanceUpdateInterval: 50   # Number of transactions after which to update the Underwriter gas balance from the rpc. 

    # EIP-1559 Transactions
    maxFeePerGas: "200000000000"                 # 'maxFeePerGas' set for all transactions (for chains that support eip-1559)

    maxAllowedPriorityFeePerGas: "100000000000"  # Upper bound to the 'maxPriorityFeePerGas' set on transactions (for chains that support eip-1559)
    maxPriorityFeeAdjustmentFactor: 1.05         # Decimal factor used to adjust the 'maxPriorityFeePerGas' returned by 'getFeeData()'. 
                                                 # The resulting value is set as the 'maxPriorityFeePerGas' property of the transaction
                                                 # if it is smaller than the configuration property 'maxAllowedPriorityFeePerGas' (if set).

    # Legacy Transactions
    maxAllowedGasPrice: "200000000000"           # Upper bound to the 'gasPrice' set on transactions (for chains that do not support eip-1559)
    gasPriceAdjustmentFactor: 1.05               # Decimal factor used to adjust the 'gasPrice' returned by 'getFeeData()'. The resulting 
                                                 # value is set as the 'gasPrice' property of the transaction if it is smaller than the 
                                                 # configuration property 'maxAllowedGasPrice' (if set).

    # All Transactions
    priorityAdjustmentFactor: 1.2                # Decimal factor used to adjust **all** the gas prices (including 'maxFeePerGas') for 
                                                 # priority transactions.


# The AMBs configuration
ambs:
  - name: mock
    enabled: true   # Defaults to 'true' if the key is missing

# Chain configuration
chains:

  - chainId: 80001
    name: "Mumbai"
    rpc: "https://polygon-mumbai-pokt.nodies.app"

    # The tokens that are to be undewritten
    tokens:
      - name: "Wrapped gas"
        address: "0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889"
        allowanceBuffer: "10000000000000000000"   # Amount by which to 'buffer' the token approvals
                                                  # to prevent having to approve tokens for every
                                                  # single underwrite. If not specified an 
                                                  # 'unlimited' approval is set.
        
        # Overrides
        lowTokenBalanceWarning: "1000000000000000000"
        tokenBalanceUpdateInterval: 50

    # Overrides
    blockDelay: 2
    listener:
      interval: 3000
      # startingBlock   # The block number at which to start 'listening' for events
    underwriter:
      retryInterval: 3000
    expirer:
      retryInterval: 3000
    wallet:
      # rpc: "https://polygon-mumbai-bor.publicnode.com"  # RPC used specifically for transaction submission. Defaults to the 'chain' rpc if not provided
      retryInterval: 3000
  

  - chainId: 11155111 
    name: "Sepolia"
    rpc: "https://eth-sepolia-public.unifra.io"
    tokens:
      - name: "Wrapped gas"
        address: "0xE67ABDA0D43f7AC8f37876bBF00D1DFadbB93aaa"
        allowanceBuffer: "10000000000000000000"

# Pools to underwrite configuration
pools:
  - id: 0           # The id given to the vault (for logs only)
    name: "Pool A"  # The name given to the vault (for logs only)
    amb: "mock"     # The AMB used for the Pool
    vaults:
      - name: "Sepolia Test Vault"    # The vault name (for logs only)
        chainId: 11155111             # The chain id in which the vault resides on
        vaultAddress: "0x6243df63dc7e97a5968578e9ae35008af3ec69df"      # The vault address
        interfaceAddress: "0xa55eAf1c45cDAbe41c374862982F1543A60A8139"  # The interface address

        # Mappings between the bytes32 channel id values used by the vault and the destination chain ids.
        channels:
          "0x0000000000000000000000000000000000000000000000000000000000013881": 80001

      - name: "Mumbai Test Vault"
        chainId: 80001
        vaultAddress: "0x6243df63dc7e97a5968578e9ae35008af3ec69df"
        interfaceAddress: "0xa55eAf1c45cDAbe41c374862982F1543A60A8139"
        channels:
          "0x0000000000000000000000000000000000000000000000000000000000AA36A7": 11155111
