services:

  underwriter:
    image: ghcr.io/catalystdao/catalyst-underwriter:testnet
    build:
      context: .
      dockerfile: dockerfile.underwriter
    volumes:
      - ./config.${NODE_ENV}.yaml:/usr/catalyst-underwriter/config.${NODE_ENV}.yaml
      - ./.env:/usr/catalyst-underwriter/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=redis
      - RELAYER_HOST=relayer
    container_name: underwriter
    restart: unless-stopped
    networks:
      - generalised-relayer_default
    logging:
      driver: 'local'
      options:
        max-size: ${MAX_LOG_SIZE:-500m}
        max-file: ${MAX_LOG_FILES:-5}

networks:
  generalised-relayer_default:
    external: true
