services:
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - ${REDIS_PORT}:${REDIS_PORT}
    attach: false

  underwriter:
    build:
      context: .
      dockerfile: dockerfile.underwriter
    volumes:
      - ./config.${NODE_ENV}.yaml:/usr/catalyst-underwriter/config.${NODE_ENV}.yaml
      - ./.env:/usr/catalyst-underwriter/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - USE_DOCKER=true
    container_name: underwriter
    restart: unless-stopped
    depends_on:
      - redis
