services:

  underwriter:
    build:
      context: .
      dockerfile: dockerfile.underwriter
    volumes:
      - ./config.${NODE_ENV}.yaml:/usr/catalyst-underwriter/config.${NODE_ENV}.yaml
      - ./.env:/usr/catalyst-underwriter/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - USE_DOCKER=true
    container_name: underwriter
    restart: unless-stopped
    networks:
      - generalisedrelayer_default

networks:
  generalisedrelayer_default:
    external: true